{{- $loggingDataRaw := .Files.Get "config/configmaps/logging-config.data.tpl" -}}
{{- $loggingData := tpl $loggingDataRaw . | fromYaml -}}
{{- $config := dict
  "name" "logging-config"
  "component" .Values.component
  "annotations" .Values.annotations
  "data" $loggingData
-}}
{{- include "sam.configMap" (dict "root" . "config" $config) }}
