{{- range $path, $_ := .Files.Glob "config/secrets/*.data.tpl" }}
{{- $secretName := base $path | trimSuffix ".data.tpl" }}
{{- $secretDataRaw := tpl ($.Files.Get $path) $ }}
{{- if $secretDataRaw }}
{{- $secretData := $secretDataRaw | fromYaml }}
{{- $config := dict
  "name" $secretName
  "component" $.Values.component
  "data" $secretData
-}}
{{- include "sam.secret" (dict "root" $ "config" $config) }}
---
{{ end }}
{{- end }}
