{{- if .Values.serviceAccount.create }}
{{- $config := dict
  "component" .Values.component
  "serviceAccount" .Values.serviceAccount
  "imagePullSecrets" .Values.imagePullSecrets
-}}
{{- include "sam.serviceAccount" (dict "root" . "config" $config) }}
{{- end }}
