{{- if .Values.gatewayDnsName }}
{{- $config := dict
  "name" .Values.gatewayDnsName
  "component" .Values.component
  "type" "ClusterIP"
  "ports" (list
    (dict "port" (.Values.gatewayPort | int) "targetPort" (.Values.gatewayPort | int) "protocol" "TCP" "name" "gateway")
  )
  "annotations" .Values.service.annotations
-}}
{{- include "sam.service" (dict "root" . "config" $config) }}
{{- end }}
