{{- if .Values.gatewayDnsName }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gatewayDnsName }}
  labels:
    {{- include "sam.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gatewayPort }}
      targetPort: {{ .Values.gatewayPort }}
      protocol: TCP
      name: gateway
  selector:
    {{- include "sam.selectorLabels" . | nindent 4 }}
{{- end }}
