apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "sam.fullname" $ }}-agent-deployer-config
    labels:
      {{- include "sam.labels" $ | nindent 4 }}
data:
    HELM_CACHE_HOME: "/tmp"
    ESCAPE_CONFIGURATION_FILE_SINGLE_QUOTE: "true"
    JSON_OBJECT_OUTPUT_FORMAT: "json"