{{- if not .Values.sam.communityMode }}
{{ include "sam.config.metadata" (dict "root" . "name" "oauth2-server-config") }}
data:
  oauth2_server.yaml: |
    log:
      stdout_log_level: INFO
      log_file_level: DEBUG
      log_file: /tmp/oauth_server.log

    !include ../shared_config.yaml

    shared_config:
      # OAuth2 service configuration
      - oauth2_config: &oauth2_config
          enabled: true
          config_file: "config/auth/oauth2_config.yaml"
          host: "0.0.0.0"
          port: 5050
          ssl_cert: ${SSL_CERTFILE}
          ssl_key: ${SSL_KEYFILE}
          ssl_passphrase: ${SSL_KEYFILE_PASSWORD}

    flows:
      # Initialize OAuth2 service
      - name: oauth2_service
        components:
          - component_name: oauth2_auth_service
            component_module: src.components.oauth2_component
            component_config:
              <<: *oauth2_config
{{- end }}
