{{- if not .Values.sam.communityMode }}
{{ include "sam.config.metadata" (dict "root" . "name" "oauth2-config") }}
data:
  oauth2_config.yaml: |
    ---
    enabled: ${OAUTH2_ENABLED:true}
    development_mode: ${OAUTH2_DEV_MODE:false}
    server:
      host: ${EXTERNAL_AUTH_HOST:localhost}
      port: 5050
      ssl:
        cert_file: ${SSL_CERTFILE:}
        key_file: ${SSL_KEYFILE:}
        ssl_passphrase: ${SSL_KEYFILE_PASSWORD:}
    providers:
      oidc:
        issuer: ${OIDC_ISSUER:https://your-provider.com}
        client_id: ${OIDC_CLIENT_ID}
        client_secret: ${OIDC_CLIENT_SECRET}
        redirect_uri: ${OIDC_REDIRECT_URI:http://localhost:8080/callback}
        scope: "openid email profile offline_access"
{{- end }}
