apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sam.fullname" . }}
  labels:
    {{- include "sam.labels" . | nindent 4 }}
  {{- include "sam.annotations" . | nindent 2 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sam.selectorLabels" . | nindent 6 }}
  strategy:
    {{- if eq .Values.rollout.strategy "RollingUpdate" }}
    {{- with .Values.rollout.rollingUpdate }}
    rollingUpdate:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    type: {{ .Values.rollout.strategy }}
  template:
    metadata:
      annotations:
        {{- include "sam.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "sam.selectorLabels" . | nindent 8 }}
        {{- include "sam.podLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: sam
          ports:
            - name: webui
              containerPort: 443
            - name: auth
              containerPort: 5050
          {{- if and .Values.environmentVariables (gt (len .Values.environmentVariables) 0) }}
          envFrom:
            - secretRef:
                name: {{ include "sam.fullname" . }}-env-vars
          {{- end }}
          command: ["solace-agent-mesh", "run", "--system-env", "/app/config/a2a_orchestrator.yaml", "/app/config/webui_backend.yaml", "/app/config/oauth2_server.yaml"]
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
            runAsUser: 999
            runAsGroup: 999
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources.sam | nindent 12 }}
          {{- end }}
          # If the application is consistently unavailable for 20 seconds, it is considered unhealthy and traffic is not sent to the pod
          readinessProbe:
            httpGet:
              path: /
              port: webui
              scheme: HTTPS
            initialDelaySeconds: 30 # Give the app time to start before probing
            successThreshold: 1
            failureThreshold: 10
            periodSeconds: 10
          # If the application is consistently down for 20 seconds it is restarted
          livenessProbe:
            httpGet:
              path: /
              port: webui
              scheme: HTTPS
            initialDelaySeconds: 30 # Give the app time to start before probing
            successThreshold: 1
            failureThreshold: 10
            periodSeconds: 10
          volumeMounts:
            - name: shared-storage
              mountPath: /tmp/solace-agent-mesh
            - name: config-volume
              mountPath: /app/config
              readOnly: true
            {{- if .Values.files }}
            {{- range .Values.files }}
            - name: {{ .name }}-volume
              mountPath: {{ .path }}
              subPath: {{ .subPath }}
              readOnly: true
            {{- end }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: shared-storage
          emptyDir: {}
        - name: config-volume
          projected:
            sources:
              - configMap:
                  name: {{ include "sam.fullname" $ }}-shared-config
              - configMap:
                  name: {{ include "sam.fullname" $ }}-oauth2-server-config
              - configMap:
                  name: {{ include "sam.fullname" $ }}-oauth2-config
              - configMap:
                  name: {{ include "sam.fullname" $ }}-orchestrator-config
              - configMap:
                  name: {{ include "sam.fullname" $ }}-webui-config
        {{- if .Values.files }}
        {{- range .Values.files }}
        - name: {{ .name }}-volume
          secret:
            secretName: {{ include "sam.fullname" $ }}-{{ .name }}
        {{- end }}
        {{- end }}
