{{- if not .Values.sam.communityMode -}}
{{- $envFrom := include "sam.agentDeployer.envFrom" . | fromYamlArray -}}
{{- $env := include "sam.agentDeployer.env" . | fromYamlArray -}}
{{- $config := dict
  "component" "agent-deployer"
  "replicaCount" 1
  "rollout" .Values.samDeployment.rollout
  "annotations" .Values.samDeployment.annotations
  "podAnnotations" .Values.samDeployment.podAnnotations
  "podLabels" .Values.samDeployment.podLabels
  "podSecurityContext" .Values.samDeployment.podSecurityContext
  "checksums" (dict
    "config" (include (print $.Template.BasePath "/configmap-agent-deployer.yaml") . | sha256sum)
    "env" (include (print $.Template.BasePath "/configmap-core-env.yaml") . | sha256sum)
    "coreSecrets" (include (print $.Template.BasePath "/secret-core.yaml") . | sha256sum)
    "envOverrides" (include (print $.Template.BasePath "/secret_env_overrides.yaml") . | sha256sum)
  )
  "serviceAccount" (dict
    "annotations" .Values.samDeployment.serviceAccount.annotations
  )
  "nodeSelector" .Values.samDeployment.nodeSelector
  "tolerations" .Values.samDeployment.tolerations
  "caInitImage" (ternary .Values.samDeployment.caInitImage .Values.samDeployment.image (not (empty .Values.samDeployment.caInitImage.repository)))
  "customCA" (dict "enabled" .Values.samDeployment.customCA.enabled "configMapName" .Values.samDeployment.customCA.configMapName)
  "volumes" (list
    (dict "name" "helm-charts" "configMap" (dict "name" (printf "%s-local-charts" (include "sam.names.fullname" .))))
  )
  "container" (dict
    "image" .Values.samDeployment.agentDeployer.image
    "ports" (list
      (dict "name" "health" "containerPort" 8089)
    )
    "envFrom" $envFrom
    "env" $env
    "securityContext" .Values.samDeployment.securityContext
    "resources" .Values.samDeployment.resources.agentDeployer
    "probes" (dict
      "startup" (dict
        "httpGet" (dict "path" "/startup" "port" 8089)
        "initialDelaySeconds" 5
        "periodSeconds" 5
        "failureThreshold" 30
      )
      "readiness" (dict
        "httpGet" (dict "path" "/readyz" "port" 8089)
        "periodSeconds" 10
        "failureThreshold" 3
      )
      "liveness" (dict
        "httpGet" (dict "path" "/healthz" "port" 8089)
        "periodSeconds" 10
        "failureThreshold" 3
      )
    )
    "volumeMounts" (list
      (dict "name" "helm-charts" "mountPath" "/opt/helm-charts" "readOnly" true)
    )
  )
-}}
{{- include "sam.deployment" (dict "root" . "config" $config) }}
{{- end }}
