apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sam.fullname" . }}-role-sam
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]