{{- if .Values.environmentVariables }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sam.fullname" $ }}-env-vars
  labels:
    {{- include "sam.labels" $ | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.environmentVariables }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}
