{{- $envVars := include "sam.utils.envAsMap" .Values.environmentVariables | fromYaml -}}
{{- if and (gt (len $envVars) 0) .Values.global.persistence.namespaceId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.persistence.namespaceId }}-env-overrides
  labels:
    {{- include "sam.labels.standard" (dict "root" . "config" (dict "component" "env-overrides")) | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $envVars }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}
