apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sam.fullname" . }}-idp-config
  labels:
    {{- include "sam.labels" . | nindent 4 }}
  {{- include "sam.annotations" . | nindent 2 }}
stringData:
  config.json: |
    {{- if .Values.config }}
    {{- if .Values.config.miniIdp }}
    {{- .Values.config.miniIdp | toJson | nindent 4 -}}
    {{- else }}
    {{- .Values.config | toJson | nindent 4 -}}
    {{- end }}
    {{- end }}
