{{- if and .Values.environmentVariables (gt (len .Values.environmentVariables) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sam.fullname" $ }}-env-vars
  labels:
    {{- include "sam.labels" $ | nindent 4 }}
type: Opaque
data:
{{- range .Values.environmentVariables }}
  {{ .key }}: {{ .value | b64enc | quote }}
{{- end }}
{{- end }}
