{{- if .Values.global.persistence.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sam.fullname" . }}-persistence
  labels:
    {{- include "sam.labels" . | nindent 4 }}
type: Opaque
data:
  WEB_UI_GATEWAY_DATABASE_URL: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" (include "sam.database.webuiUser" .) (include "sam.database.webuiPassword" .) (include "postgresql.host" (index .Subcharts "persistence-layer")) (include "postgresql.port" (index .Subcharts "persistence-layer")) (include "sam.database.webuiName" .) | b64enc }}
  ORCHESTRATOR_DATABASE_URL: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" (include "sam.database.orchestratorUser" .) (include "sam.database.orchestratorPassword" .) (include "postgresql.host" (index .Subcharts "persistence-layer")) (include "postgresql.port" (index .Subcharts "persistence-layer")) (include "sam.database.orchestratorName" .) | b64enc }}
  S3_ENDPOINT_URL: {{ include "seaweedfs.s3url" (index .Subcharts "persistence-layer") | b64enc }}
  S3_BUCKET_NAME: {{ include "sam.s3.bucketName" . | b64enc }}
  AWS_ACCESS_KEY_ID: {{ include "sam.s3.accessKey" . | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ include "sam.s3.secretKey" . | b64enc }}
  AWS_REGION: {{ "us-east-1" | b64enc }}
{{- end }}