{{- if and .Values.environmentVariables .Values.global.persistence.namespaceId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.persistence.namespaceId }}-env-overrides
  labels:
    {{- include "sam.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.environmentVariables }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}
