apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sam.fullname" $ }}-environment
  labels:
    {{- include "sam.labels" $ | nindent 4 }}
type: Opaque
data:
  # Namespace configuration
  NAMESPACE: {{ .Release.Namespace | b64enc | quote }}

  # Solace Broker configuration
  SOLACE_BROKER_URL: {{ .Values.broker.url | b64enc | quote }}
  SOLACE_BROKER_USERNAME: {{ .Values.broker.clientUsername | b64enc | quote }}
  SOLACE_BROKER_PASSWORD: {{ .Values.broker.password | b64enc | quote }}
  SOLACE_BROKER_VPN: {{ .Values.broker.vpn | b64enc | quote }}
  SOLACE_DEV_MODE: {{ "false" | b64enc | quote }}
  USE_TEMPORARY_QUEUES: {{ "false" | b64enc | quote }}

  # LLM Service configuration
  LLM_SERVICE_PLANNING_MODEL_NAME: {{ .Values.llmService.planningModel | b64enc | quote }}
  LLM_SERVICE_GENERAL_MODEL_NAME: {{ .Values.llmService.generalModel | b64enc | quote }}
  LLM_REPORT_MODEL_NAME: {{ .Values.llmService.reportModel | b64enc | quote }}
  LLM_SERVICE_ENDPOINT: {{ .Values.llmService.llmServiceEndpoint | b64enc | quote }}
  LLM_SERVICE_API_KEY: {{ .Values.llmService.llmServiceApiKey | b64enc | quote }}

  # Image models (defaults to LLM service)
  IMAGE_MODEL_NAME: {{ .Values.llmService.imageModel | b64enc | quote }}
  IMAGE_DESCRIPTION_MODEL_NAME: {{ .Values.llmService.planningModel | b64enc | quote }}
  IMAGE_SERVICE_ENDPOINT: {{ .Values.llmService.llmServiceEndpoint | b64enc | quote }}
  IMAGE_SERVICE_API_KEY: {{ .Values.llmService.llmServiceApiKey | b64enc | quote }}

  # Audio transcription (defaults to LLM service)
  AUDIO_TRANSCRIPTION_MODEL_NAME: {{ .Values.llmService.transcriptionModel | b64enc | quote }}
  AUDIO_TRANSCRIPTION_API_BASE: {{ .Values.llmService.llmServiceEndpoint | b64enc | quote }}
  AUDIO_TRANSCRIPTION_API_KEY: {{ .Values.llmService.llmServiceApiKey | b64enc | quote }}

  # WebUI Gateway configuration
  WEBUI_GATEWAY_ID: {{ printf "%s-gateway" (include "sam.fullname" $) | b64enc | quote }}
  FASTAPI_HOST: {{ "0.0.0.0" | b64enc | quote }}
  FASTAPI_PORT: {{ "8000" | b64enc | quote }}
  FASTAPI_HTTPS_PORT: {{ "8443" | b64enc | quote }}
  SESSION_SECRET_KEY: {{ .Values.sam.sessionSecretKey | b64enc | quote }}

  # Frontend configuration
  FRONTEND_WELCOME_MESSAGE: {{ "How can I assist you today?" | b64enc | quote }}
  FRONTEND_BOT_NAME: {{ "Solace Agent Mesh" | b64enc | quote }}
  FRONTEND_COLLECT_FEEDBACK: {{ "false" | b64enc | quote }}

  # Gateway artifact handling
  ENABLE_EMBED_RESOLUTION: {{ "true" | b64enc | quote }}
  GATEWAY_ARTIFACT_LIMIT_BYTES: {{ "10000000" | b64enc | quote }}

  # TLS/SSL configuration
  {{- if .Values.service.tls.enabled }}
  SSL_CERTFILE: {{ "/app/certs/tls.crt" | b64enc | quote }}
  SSL_KEYFILE: {{ "/app/certs/tls.key" | b64enc | quote }}
  SSL_KEYFILE_PASSWORD: {{ .Values.service.tls.passphrase | b64enc | quote }}
  {{- else }}
  SSL_CERTFILE: {{ "" | b64enc | quote }}
  SSL_KEYFILE: {{ "" | b64enc | quote }}
  SSL_KEYFILE_PASSWORD: {{ "" | b64enc | quote }}
  {{- end }}

  {{- if .Values.sam.enterprise }}
  # External authentication (Enterprise only)
  # OAuth2 configuration (Enterprise only)
  {{- if and .Values.sam.oauthProvider.oidc .Values.sam.oauthProvider.oidc.issuer }}
  OAUTH2_ENABLED: {{ "true" | b64enc | quote }}
  FRONTEND_USE_AUTHORIZATION: {{ "true" | b64enc | quote }}
  {{- else }}
  OAUTH2_ENABLED: {{ "false" | b64enc | quote }}
  FRONTEND_USE_AUTHORIZATION: {{ "false" | b64enc | quote }}
  {{- end }}
  {{- /* Compute external URLs based on Ingress vs Service exposure */ -}}
  {{- $serviceDns := printf "%s.%s.svc.cluster.local" (include "sam.fullname" $) .Release.Namespace }}
  {{- $externalHost := "" }}
  {{- $externalScheme := "" }}
  {{- $externalBaseUrl := "" }}
  {{- $authCallbackUrl := "" }}
  {{- $authServiceUrl := "" }}

  {{- if .Values.ingress.enabled }}
    {{- /* When Ingress is enabled, use standard HTTP/HTTPS ports (no port in URL) */ -}}
    {{- $ingressHost := "" }}
    {{- range .Values.ingress.hosts }}
      {{- if .host }}
        {{- $ingressHost = .host }}
      {{- end }}
    {{- end }}
    {{- $externalHost = $ingressHost | default .Values.sam.dnsName | default $serviceDns }}
    {{- /* Use HTTPS if Ingress has TLS config or annotations indicate TLS (ALB cert-arn) */ -}}
    {{- $hasIngressTls := or (and .Values.ingress.tls (gt (len .Values.ingress.tls) 0)) (and .Values.ingress.annotations (hasKey .Values.ingress.annotations "alb.ingress.kubernetes.io/certificate-arn")) }}
    {{- $externalScheme = ternary "https" "http" $hasIngressTls }}
    {{- $externalBaseUrl = printf "%s://%s" $externalScheme $externalHost }}
    {{- $authCallbackUrl = printf "%s/api/v1/auth/callback" $externalBaseUrl }}
    {{- $authServiceUrl = $externalBaseUrl }}
  {{- else }}
    {{- /* When using Service (LoadBalancer/NodePort), use explicit ports */ -}}
    {{- $externalHost = .Values.sam.dnsName | default $serviceDns }}
    {{- $externalScheme = ternary "https" "http" .Values.service.tls.enabled }}
    {{- $servicePort := "443" }}
    {{- $authPort := "5050" }}
    {{- $externalBaseUrl = printf "%s://%s:%s" $externalScheme $externalHost $servicePort }}
    {{- $authCallbackUrl = printf "%s://%s:%s/api/v1/auth/callback" $externalScheme $externalHost $servicePort }}
    {{- $authServiceUrl = printf "%s://%s:%s" $externalScheme $externalHost $authPort }}
  {{- end }}

  WEBUI_FRONTEND_SERVER_URL : {{ $externalBaseUrl | b64enc | quote }}
  WEBUI_FRONTEND_URL : {{ $externalBaseUrl | b64enc | quote }}
  EXTERNAL_AUTH_CALLBACK: {{ $authCallbackUrl | b64enc | quote }}
  FRONTEND_REDIRECT_URL: {{ $externalBaseUrl | b64enc | quote }}
  EXTERNAL_AUTH_SERVICE_URL: {{ $authServiceUrl | b64enc | quote }}
  EXTERNAL_AUTH_HOST: {{ $externalHost | b64enc | quote }}

  # OIDC configuration (Enterprise only)
  EXTERNAL_AUTH_PROVIDER: {{ "oidc" | b64enc | quote }}
  OIDC_ISSUER: {{ .Values.sam.oauthProvider.oidc.issuer | b64enc | quote }}
  OIDC_CLIENT_ID: {{ .Values.sam.oauthProvider.oidc.clientId | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.sam.oauthProvider.oidc.clientSecret | b64enc | quote }}
  OIDC_REDIRECT_URI: {{ $authCallbackUrl | b64enc | quote }}

  DEPLOY_COMMAND: {{ printf "echo '{{ configurationFile }}' > /tmp/agent-deploy-{{ id }}.yaml && helm install sam-agent-{{ id }} https://solaceproducts.github.io/solace-agent-mesh-helm-quickstart/sam-agent-1.0.3.tgz --set-json 'environmentVariables={{ values }}' --set agentId={{ id }} --set-file config.agentYaml=/tmp/agent-deploy-{{ id }}.yaml --set solaceBroker.url=${SOLACE_BROKER_URL} --set solaceBroker.username=${SOLACE_BROKER_USERNAME} --set solaceBroker.password=${SOLACE_BROKER_PASSWORD} --set solaceBroker.vpn=${SOLACE_BROKER_VPN} --set llmService.generalModelName=${LLM_SERVICE_GENERAL_MODEL_NAME} --set llmService.endpoint=${LLM_SERVICE_ENDPOINT} --set llmService.apiKey=${LLM_SERVICE_API_KEY} --set image.repository=%s --set image.tag=%s --set global.persistence.namespaceId=%s" .Values.samDeployment.image.repository .Values.samDeployment.image.tag .Values.global.persistence.namespaceId | b64enc | quote }}
  UPDATE_COMMAND: {{ printf "echo '{{ configurationFile }}' > /tmp/agent-update-{{ id }}.yaml && helm upgrade -i sam-agent-{{ id }} https://solaceproducts.github.io/solace-agent-mesh-helm-quickstart/sam-agent-1.0.3.tgz --set-json 'environmentVariables={{ values }}' --set agentId={{ id }} --set-file config.agentYaml=/tmp/agent-update-{{ id }}.yaml --set solaceBroker.url=${SOLACE_BROKER_URL} --set solaceBroker.username=${SOLACE_BROKER_USERNAME} --set solaceBroker.password=${SOLACE_BROKER_PASSWORD} --set solaceBroker.vpn=${SOLACE_BROKER_VPN} --set llmService.generalModelName=${LLM_SERVICE_GENERAL_MODEL_NAME} --set llmService.endpoint=${LLM_SERVICE_ENDPOINT} --set llmService.apiKey=${LLM_SERVICE_API_KEY} --set image.repository=%s --set image.tag=%s --set global.persistence.namespaceId=%s" .Values.samDeployment.image.repository .Values.samDeployment.image.tag .Values.global.persistence.namespaceId | b64enc | quote }}
  STATUS_COMMAND: {{ printf "helm status sam-agent-{{ id }} -o json" | b64enc | quote }}
  UNDEPLOY_COMMAND: {{ printf "helm delete sam-agent-{{ id }}" | b64enc | quote }}

  OAUTH2_DEV_MODE: {{ "false" | b64enc | quote }}
  {{- end }}

  # Custom environment variables from values.yaml
  {{- if .Values.environmentVariables }}
  {{- if kindIs "map" .Values.environmentVariables }}
  {{- range $key, $value := .Values.environmentVariables }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
  {{- else if kindIs "string" .Values.environmentVariables }}
  {{- $envVars := .Values.environmentVariables }}
  {{- range $line := splitList "\n" $envVars }}
  {{- if $line }}
  {{- $parts := splitn "=" 2 $line }}
  {{- if eq (len $parts) 2 }}
  {{ index $parts 0 | trim }}: {{ index $parts 1 | trim | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
