{{- include "sam.validateApplicationPassword" . }}
{{ include "sam.secret.metadata" (dict "root" . "name" "database" "component" "database") }}
data:
  {{- include "sam.secret.databaseData" . | nindent 2 }}
