{{- if not .Values.sam.communityMode }}
{{ include "sam.secret.metadata" (dict "root" . "name" "auth-secrets" "component" "auth") }}
data:
  OIDC_ISSUER: {{ .Values.sam.oauthProvider.oidc.issuer | b64enc | quote }}
  OIDC_CLIENT_ID: {{ .Values.sam.oauthProvider.oidc.clientId | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.sam.oauthProvider.oidc.clientSecret | b64enc | quote }}
  {{- $urls := include "sam.urls.compute" . | fromYaml }}
  OIDC_REDIRECT_URI: {{ $urls.authCallbackUrl | b64enc | quote }}
{{- end }}
