apiVersion: v1
kind: Service
metadata:
  name: {{ include "sam.fullname" . }}
  labels:
    {{- include "sam.labels" . | nindent 4 }}
    app: solace
    {{- if .Values.deploymentId }}
    deploymentId: {{ .Values.deploymentId | quote }}
    {{- end }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.service.dns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.dns.hostname }}
    external-dns.alpha.kubernetes.io/ttl: {{ .Values.service.dns.ttl | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: webui
    - port: 5050
      targetPort: auth
      protocol: TCP
      name: auth
    {{- if .Values.solaceA2ALogin.enabled }}
    - port: {{ .Values.solaceA2ALogin.service.port | default 3000 }}
      targetPort: a2alogin
      protocol: TCP
      name: solace-a2a-login
    {{- end }}
  selector:
    {{- include "sam.selectorLabels" . | nindent 4 }}
