{{- $config := dict
  "component" "core"
  "type" .Values.service.type
  "annotations" .Values.service.annotations
  "ports" (include "sam.service.ports" . | fromYamlArray)
-}}
{{- include "sam.service" (dict "root" . "config" $config) }}
