{{- if eq (.Values.sam.platform | default "python") "go" }}
{{- $strConfig := dict
  "component" "str"
  "serviceAccount" (dict "name" .Values.samDeployment.serviceAccount.name "annotations" .Values.samDeployment.serviceAccount.annotations)
  "imagePullSecrets" (ternary (list .Values.samDeployment.imagePullSecret) nil (not (empty .Values.samDeployment.imagePullSecret)))
-}}
{{ include "sam.serviceAccount" (dict "root" . "config" $strConfig) }}
{{- end }}
