{{- if not .Values.sam.communityMode }}
{{- $deployerConfig := dict
  "component" "agent-deployer"
  "serviceAccount" (dict "annotations" .Values.samDeployment.serviceAccount.annotations)
  "imagePullSecrets" (ternary (list .Values.samDeployment.imagePullSecret) nil (not (empty .Values.samDeployment.imagePullSecret)))
-}}
{{ include "sam.serviceAccount" (dict "root" . "config" $deployerConfig) }}
{{- end }}
