{{- if (include "sam.broker.embedded" .) }}
{{- $brokerConfig := dict
  "component" "broker"
  "imagePullSecrets" (ternary (list .Values.samDeployment.imagePullSecret) nil (not (empty .Values.samDeployment.imagePullSecret)))
-}}
{{ include "sam.serviceAccount" (dict "root" . "config" $brokerConfig) }}
{{- end }}
