{{- if (include "sam.broker.embedded" .) -}}
{{- $config := dict
  "component" "broker"
  "clusterIP" "None"
  "ports" (list
    (dict "port" 55555 "targetPort" 55555 "name" "smf" "protocol" "TCP")
    (dict "port" 8080 "targetPort" 8080 "name" "semp" "protocol" "TCP")
  )
-}}
{{- include "sam.service" (dict "root" . "config" $config) }}
{{- end }}
