{{- $coreConfig := dict
  "component" "core"
  "serviceAccount" (dict "name" .Values.samDeployment.serviceAccount.name "annotations" .Values.samDeployment.serviceAccount.annotations)
  "imagePullSecrets" (ternary (list .Values.samDeployment.imagePullSecret) nil (not (empty .Values.samDeployment.imagePullSecret)))
-}}
{{ include "sam.serviceAccount" (dict "root" . "config" $coreConfig) }}
