{{- if .Values.solaceA2ALogin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sam.fullname" . }}-solace-a2a-login
  labels:
    {{- include "sam.labels" . | nindent 4 }}
    app.kubernetes.io/component: solace-a2a-login
  {{- include "sam.annotations" . | nindent 2 }}
spec:
  replicas: {{ .Values.solaceA2ALogin.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "sam.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: solace-a2a-login
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      annotations:
        {{- include "sam.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "sam.selectorLabels" . | nindent 8 }}
        {{- include "sam.podLabels" . | nindent 8 }}
        app.kubernetes.io/component: solace-a2a-login
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: solace-a2a-login
          image: "{{- if .Values.solaceA2ALogin.image.registry }}{{ .Values.solaceA2ALogin.image.registry }}/{{ end }}{{ .Values.solaceA2ALogin.image.repository }}:{{ .Values.solaceA2ALogin.image.tag }}"
          imagePullPolicy: {{ .Values.solaceA2ALogin.image.pullPolicy | default "Always" }}
          ports:
            - name: a2alogin
              containerPort: 3000
              protocol: TCP
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.solaceA2ALogin.resources }}
          resources:
            {{- toYaml .Values.solaceA2ALogin.resources | nindent 12 }}
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: a2alogin
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: a2alogin
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          envFrom:
            - secretRef:
                name: {{ include "sam.fullname" . }}-solace-a2a-login-env
          volumeMounts:
            {{- if .Values.files }}
            {{- range .Values.files }}
            - name: {{ .name }}-volume
              mountPath: {{ .path }}
              subPath: {{ .subPath }}
              readOnly: true
            {{- end }}
            {{- end }}
            - name: config-volume
              mountPath: /app/config.json
              subPath: config.json
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.files }}
        {{- range .Values.files }}
        - name: {{ .name }}-volume
          secret:
            secretName: {{ include "sam.fullname" $ }}-{{ .name }}
        {{- end }}
        {{- end }}
        - name: config-volume
          secret:
            secretName: {{ include "sam.fullname" . }}-idp-config
{{- end }}