{{- if (include "sam.broker.embedded" .) -}}
{{- $brokerName := include "sam.names.component" (dict "root" . "component" "broker") -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $brokerName }}
  labels:
    {{- include "sam.labels.standard" (dict "root" . "config" (dict "component" "broker")) | nindent 4 }}
spec:
  serviceName: {{ $brokerName }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "sam.labels.matchLabels" (dict "root" . "component" "broker") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sam.labels.matchLabels" (dict "root" . "component" "broker") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "sam.names.serviceAccount" (dict "root" . "config" (dict "component" "broker")) }}
      {{- include "sam.images.pullSecrets" (dict "root" . "pullSecrets" .Values.embeddedBroker.imagePullSecrets) | nindent 6 }}
      terminationGracePeriodSeconds: 60
      securityContext:
        {{- include "sam.security.podContext" dict | nindent 8 }}
      containers:
      - name: broker
        image: {{ include "sam.images.image" (dict "root" . "image" .Values.embeddedBroker.image) | quote }}
        imagePullPolicy: IfNotPresent
        command: ["/usr/sbin/boot.sh"]
        env:
        - name: username_admin_password
          valueFrom:
            secretKeyRef:
              name: {{ include "sam.names.fullname" . }}-core-secrets
              key: BROKER_ADMIN_PASSWORD
        - name: username_admin_globalaccesslevel
          value: "admin"
        - name: system_scaling_maxconnectioncount
          value: "100"
        ports:
        - name: smf
          containerPort: 55555
        - name: semp
          containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        lifecycle:
          preStop:
            exec:
              command:
              - bash
              - -ec
              - |
                while ! pgrep solacedaemon ; do sleep 1; done
                killall solacedaemon;
                while [ ! -d /usr/sw/var.upgrade ]; do sleep 1; done;
        resources:
        {{- if .Values.embeddedBroker.resources }}
          {{- toYaml .Values.embeddedBroker.resources | nindent 10 }}
        {{- else }}
          requests:
            cpu: "2"
            memory: 2480Mi
          limits:
            cpu: "2"
            memory: 2480Mi
        {{- end }}
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 300
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health-check/guaranteed-active
            port: 5550
          initialDelaySeconds: 30
          periodSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /var/lib/solace
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: {{ .Values.embeddedBroker.shmSize | default "1Gi" }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        {{- include "sam.labels.matchLabels" (dict "root" . "component" "broker") | nindent 8 }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.embeddedBroker.storageClassName }}
      storageClassName: {{ .Values.embeddedBroker.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: 7Gi
{{- end }}
