apiVersion: v2
name: test-sam-common
description: A Helm chart for Kubernetes to test sam-common
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: sam-common
    version: 1.1.0
    repository: file://../sam-common