import React from 'react';
import Content from '@theme-original/DocItem/Content';
import type ContentType from '@theme/DocItem/Content';
import type {WrapperProps} from '@docusaurus/types';
import LegacyVersionNotice from '@site/src/components/LegacyVersionNotice';

type Props = WrapperProps<typeof ContentType>;

// GENERATED by deprecate.py (DATAGO-147013): render the deprecation notice at the top
// of every doc page's content. Site-wide noindex stays set in docusaurus.config.ts.
export default function ContentWrapper(props: Props): JSX.Element {
  return (
    <>
      <LegacyVersionNotice />
      <Content {...props} />
    </>
  );
}
